"""
Background Tasks Package
Celery + Redis for async task processing

Features:
- Async task execution
- Task scheduling
- Result backend
- Task monitoring

Generated by inquantic-foundry
"""

from tasks.worker import celery_app

__all__ = ["celery_app"]