"""
Health Check Tests
Tests for health, readiness, and liveness endpoints

Generated by inquantic-foundry
"""

import pytest
from httpx import AsyncClient


# ============================================================================
# HEALTH CHECK TESTS
# ============================================================================

@pytest.mark.asyncio
async def test_health_check(client: AsyncClient):
    """Test health check endpoint"""
    response = await client.get("/api/v1/health")

    assert response.status_code == 200
    data = response.json()

    assert "status" in data
    assert data["status"] == "healthy"
    assert "timestamp" in data
    assert "version" in data
    assert "dependencies" in data


@pytest.mark.asyncio
async def test_readiness_check(client: AsyncClient):
    """Test Kubernetes readiness probe"""
    response = await client.get("/api/v1/ready")

    assert response.status_code == 200
    data = response.json()

    assert "status" in data
    assert data["status"] == "ready"


@pytest.mark.asyncio
async def test_liveness_check(client: AsyncClient):
    """Test Kubernetes liveness probe"""
    response = await client.get("/api/v1/live")

    assert response.status_code == 200
    data = response.json()

    assert "status" in data
    assert data["status"] == "alive"


# ============================================================================
# ROOT ENDPOINT TESTS
# ============================================================================

@pytest.mark.asyncio
async def test_root_endpoint(client: AsyncClient):
    """Test root endpoint"""
    response = await client.get("/")

    assert response.status_code == 200
    data = response.json()

    assert "service" in data
    assert "version" in data
    assert "status" in data
    assert data["status"] == "operational"


# ============================================================================
# EXAMPLE ENDPOINT TESTS
# ============================================================================

@pytest.mark.asyncio
async def test_example_endpoint(client: AsyncClient):
    """Test example GET endpoint"""
    response = await client.get("/api/v1/example")

    assert response.status_code == 200
    data = response.json()

    assert "message" in data
    assert "data" in data


@pytest.mark.asyncio
async def test_example_post_endpoint(client: AsyncClient):
    """Test example POST endpoint"""
    response = await client.post("/api/v1/example")

    assert response.status_code == 201
    data = response.json()

    assert "message" in data
    assert data["message"] == "Resource created successfully"


# ============================================================================
# ERROR HANDLING TESTS
# ============================================================================

@pytest.mark.asyncio
async def test_404_error(client: AsyncClient):
    """Test 404 error handling"""
    response = await client.get("/api/v1/nonexistent")

    assert response.status_code == 404


@pytest.mark.asyncio
async def test_method_not_allowed(client: AsyncClient):
    """Test 405 error (method not allowed)"""
    response = await client.put("/api/v1/health")

    assert response.status_code == 405


# ============================================================================
# CORS TESTS
# ============================================================================

@pytest.mark.asyncio
async def test_cors_headers(client: AsyncClient):
    """Test CORS headers are present"""
    response = await client.options(
        "/api/v1/health",
        headers={
            "Origin": "http://localhost:3000",
            "Access-Control-Request-Method": "GET"
        }
    )

    assert "access-control-allow-origin" in response.headers


# ============================================================================
# PERFORMANCE TESTS
# ============================================================================

@pytest.mark.asyncio
@pytest.mark.slow
async def test_health_check_performance(client: AsyncClient):
    """Test health check responds quickly"""
    import time

    start = time.time()
    response = await client.get("/api/v1/health")
    duration = time.time() - start

    assert response.status_code == 200
    assert duration < 0.5  # Should respond in less than 500ms


# ============================================================================
# INTEGRATION TESTS
# ============================================================================

@pytest.mark.asyncio
@pytest.mark.integration
async def test_multiple_concurrent_requests(client: AsyncClient):
    """Test handling multiple concurrent requests"""
    import asyncio

    async def make_request():
        return await client.get("/api/v1/health")

    # Make 10 concurrent requests
    responses = await asyncio.gather(*[make_request() for _ in range(10)])

    # All should succeed
    for response in responses:
        assert response.status_code == 200