"""
Email Service Tests
Unit tests for email functionality

Generated by inquantic-foundry
"""

import pytest
from unittest.mock import patch, MagicMock, AsyncMock
from pathlib import Path

from email.service import EmailService, email_service
from email.templates import render_template


class TestEmailService:
    """Test EmailService class"""

    def test_email_service_initialization(self):
        """Test service initializes with correct settings"""
        service = EmailService()
        assert service.host is not None
        assert service.port > 0
        assert service.from_email is not None

    @pytest.mark.asyncio
    async def test_send_async_success(self):
        """Test async email sending succeeds"""
        with patch("email.service.aiosmtplib.SMTP") as mock_smtp:
            # Setup mock
            mock_instance = AsyncMock()
            mock_smtp.return_value = mock_instance

            # Test send
            result = await email_service.send_async(
                to_email="test@example.com",
                subject="Test Email",
                html_body="<p>Test content</p>",
            )

            assert result is True
            mock_instance.connect.assert_called_once()
            mock_instance.send_message.assert_called_once()
            mock_instance.quit.assert_called_once()

    def test_send_sync_success(self):
        """Test sync email sending succeeds"""
        with patch("email.service.smtplib.SMTP") as mock_smtp:
            # Setup mock
            mock_instance = MagicMock()
            mock_smtp.return_value = mock_instance

            # Test send
            result = email_service.send_sync(
                to_email="test@example.com",
                subject="Test Email",
                html_body="<p>Test content</p>",
            )

            assert result is True
            mock_instance.send_message.assert_called_once()
            mock_instance.quit.assert_called_once()

    def test_create_message(self):
        """Test MIME message creation"""
        service = EmailService()
        msg = service._create_message(
            to_email="test@example.com",
            subject="Test",
            html_body="<p>HTML</p>",
            text_body="Plain text",
        )

        assert msg["To"] == "test@example.com"
        assert msg["Subject"] == "Test"
        assert msg["From"] is not None


class TestTemplates:
    """Test email templates"""

    def test_render_welcome_template(self):
        """Test welcome template renders correctly"""
        context = {
            "user_name": "John Doe",
            "user_email": "john@example.com",
            "verification_link": "https://example.com/verify/token123",
        }

        html = render_template("welcome.html", context)

        assert "John Doe" in html
        assert "john@example.com" in html
        assert "https://example.com/verify/token123" in html
        assert "Welcome" in html

    def test_render_password_reset_template(self):
        """Test password reset template renders correctly"""
        context = {
            "user_name": "Jane Doe",
            "reset_link": "https://example.com/reset/token456",
            "expiry_hours": "2",
        }

        html = render_template("password_reset.html", context)

        assert "Jane Doe" in html
        assert "https://example.com/reset/token456" in html
        assert "2 hours" in html
        assert "Password Reset" in html

    def test_render_notification_template(self):
        """Test notification template renders correctly"""
        context = {
            "user_name": "Bob Smith",
            "subject": "Important Update",
            "message": "<p>This is a test notification</p>",
            "action_link": "https://example.com/action",
            "action_text": "View Update",
        }

        html = render_template("notification.html", context)

        assert "Bob Smith" in html
        assert "Important Update" in html
        assert "test notification" in html
        assert "https://example.com/action" in html

    def test_template_not_found(self):
        """Test error handling for missing template
"""
        with pytest.raises(Exception):
            render_template("nonexistent.html", {})


@pytest.mark.asyncio
async def test_send_template_email_async():
    """Test template-based email sending (async)"""
    with patch("email.service.aiosmtplib.SMTP") as mock_smtp:
        mock_instance = AsyncMock()
        mock_smtp.return_value = mock_instance

        result = await email_service.send_template_async(
            to_email="test@example.com",
            subject="Welcome!",
            template_name="welcome.html",
            context={
                "user_name": "Test User",
                "user_email": "test@example.com",
                "verification_link": "https://example.com/verify",
            },
        )

        assert result is True
        mock_instance.send_message.assert_called_once()


def test_send_template_email_sync():
    """Test template-based email sending (sync)"""
    with patch("email.service.smtplib.SMTP") as mock_smtp:
        mock_instance = MagicMock()
        mock_smtp.return_value = mock_instance

        result = email_service.send_template_sync(
            to_email="test@example.com",
            subject="Welcome!",
            template_name="welcome.html",
            context={
                "user_name": "Test User",
                "user_email": "test@example.com",
                "verification_link": "https://example.com/verify",
            },
        )

        assert result is True
        mock_instance.send_message.assert_called_once()
