"""
RBAC/ABAC Authorization Module
Using Casbin for enterprise-grade access control

Supports:
- RBAC (Role-Based Access Control)
- ABAC (Attribute-Based Access Control)
- PBAC (Policy-Based Access Control)

Generated by inquantic-foundry
"""

import casbin
from pathlib import Path
from typing import List, Optional, Union
from fastapi import Depends, HTTPException, status

from app.api.deps import get_current_user
from db.models.auth import User
from app_logging.logger import get_logger

logger = get_logger(__name__)

# ... (Previous code remains unchanged until require_permission) ...

# ============================================================================
# FASTAPI DEPENDENCIES
# ============================================================================

def require_permission(resource: str, action: str):
    """
    FastAPI dependency factory for permission checking.
    """

    async def permission_checker(current_user: User = Depends(get_current_user)):
        user_id = str(current_user.id)
        # Adapt single role to list for compatibility with RBAC logic
        roles = [current_user.role.value] if current_user.role else []

        # Check user-specific permission
        if check_permission(user_id, resource, action):
            return current_user

        # Check role-based permissions
        for role in roles:
            # Check mixed case or specific format if needed. 
            # Usually roles in Casbin are stored as "role:admin" or just "admin" depending on policy.
            # The check_role_permission helper adds "role:" prefix.
            if check_permission(f"role:{role}", resource, action):
                return current_user

        logger.warning(
            "permission_denied",
            user_id=user_id,
            resource=resource,
            action=action,
            roles=roles
        )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Permission denied: {action} on {resource}"
        )

    return permission_checker


def require_role(required_role: str):
    """
    FastAPI dependency factory for role checking.
    """

    async def role_checker(current_user: User = Depends(get_current_user)):
        # Adapt single role to list
        user_roles = [current_user.role.value] if current_user.role else []

        if required_role in user_roles:
            return current_user

        logger.warning(
            "role_check_failed",
            user_id=str(current_user.id),
            required_role=required_role,
            user_roles=user_roles
        )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Role '{required_role}' required"
        )

    return role_checker


# ============================================================================
# EXAMPLE USAGE IN ROUTES
# ============================================================================

"""
# In your router file:

from fastapi import APIRouter, Depends
from security.rbac import require_permission, require_role

router = APIRouter()

# Require specific permission
@router.get("/patients/{patient_id}", dependencies=[Depends(require_permission("patients:*", "read"))])
async def get_patient(patient_id: str):
    return {"patient_id": patient_id}

# Require specific role
@router.get("/admin/dashboard", dependencies=[Depends(require_role("admin"))])
async def admin_dashboard():
    return {"message": "Admin dashboard"}

# Check permission in route logic
@router.post("/data")
async def create_data(current_user: dict = Depends(get_current_user)):
    user_id = current_user["sub"]

    if not check_permission(user_id, "data:own", "create"):
        raise HTTPException(status_code=403, detail="Permission denied")

    # Create data...
    return {"message": "Data created"}
"""