"""initial_baseline

Revision ID: d25d67015462
Revises: 
Create Date: 2026-01-09 11:47:26.367096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd25d67015462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_active', table_name='sessions', schema='auth')
    op.drop_index('idx_sessions_refresh_token', table_name='sessions', schema='auth')
    op.drop_index('idx_sessions_user_id', table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.alter_column('conversation_logs', 'conversation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Raw conversation data from submission',
               existing_nullable=False,
               schema='assessment')
    op.drop_index('idx_conversation_logs_response_id', table_name='conversation_logs', schema='assessment')
    op.alter_column('pools', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name/title of the pool',
               existing_nullable=False,
               schema='assessment')
    op.alter_column('pools', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description of what this pool contains',
               existing_nullable=True,
               schema='assessment')
    op.alter_column('pools', 'order_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order of pools',
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='assessment')
    op.alter_column('pools', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this pool is active/visible',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='assessment')
    op.drop_index('idx_pools_active', table_name='pools', schema='assessment')
    op.drop_index('idx_pools_order', table_name='pools', schema='assessment')
    op.create_index(op.f('ix_assessment_pools_created_at'), 'pools', ['created_at'], unique=False, schema='assessment')
    op.drop_table_comment(
        'pools',
        existing_comment='Pool containers that group multiple assessment sections',
        schema='assessment'
    )
    op.alter_column('question_answers', 'translated_answer',
               existing_type=sa.TEXT(),
               comment='English translation of the answer if provided in another language',
               existing_nullable=True,
               schema='assessment')
    op.alter_column('responses', 'unanswered_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               comment='Array of question objects that were not answered in the conversation',
               existing_server_default=sa.text("'[]'::jsonb"),
               schema='assessment')
    op.alter_column('responses', 'assessment_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='assessment')
    op.alter_column('responses', 'last_conversation_id',
               existing_type=sa.UUID(),
               comment='ID of the most recent conversation log, overwritten on resume (not a FK to avoid circular dependency)',
               existing_comment='ID of the most recent conversation log, overwritten on resume',
               existing_nullable=True,
               schema='assessment')
    op.drop_index('idx_responses_last_conversation_id', table_name='responses', schema='assessment')
    op.drop_index('idx_sections_pool_id', table_name='sections', schema='assessment')
    op.alter_column('parents', 'assigned_doctor_id',
               existing_type=sa.UUID(),
               comment='Assigned doctor (optional, can be set later)',
               existing_nullable=True,
               schema='clinical')
    op.drop_index('idx_final_reports_child', table_name='final_reports', schema='report')
    op.drop_index('idx_final_reports_doctor_reviewed', table_name='final_reports', schema='report')
    op.drop_index('idx_final_reports_generated', table_name='final_reports', schema='report')
    op.drop_index('idx_final_reports_hod_reviewed', table_name='final_reports', schema='report')
    op.create_index(op.f('ix_report_final_reports_created_at'), 'final_reports', ['created_at'], unique=False, schema='report')
    op.drop_table_comment(
        'final_reports',
        existing_comment='Comprehensive AI-generated final reports combining all pool summaries with two-stage review workflow',
        schema='report'
    )
    op.drop_index('idx_pool_summaries_child', table_name='pool_summaries', schema='report')
    op.drop_index('idx_pool_summaries_generated', table_name='pool_summaries', schema='report')
    op.drop_index('idx_pool_summaries_pool', table_name='pool_summaries', schema='report')
    op.drop_constraint('uq_child_pool_summary', 'pool_summaries', schema='report', type_='unique')
    op.create_index(op.f('ix_report_pool_summaries_created_at'), 'pool_summaries', ['created_at'], unique=False, schema='report')
    op.drop_table_comment(
        'pool_summaries',
        existing_comment='AI-generated summaries for completed assessment pools',
        schema='report'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'pool_summaries',
        'AI-generated summaries for completed assessment pools',
        existing_comment=None,
        schema='report'
    )
    op.drop_index(op.f('ix_report_pool_summaries_created_at'), table_name='pool_summaries', schema='report')
    op.create_unique_constraint('uq_child_pool_summary', 'pool_summaries', ['child_id', 'pool_id'], schema='report')
    op.create_index('idx_pool_summaries_pool', 'pool_summaries', ['pool_id'], unique=False, schema='report')
    op.create_index('idx_pool_summaries_generated', 'pool_summaries', ['generated_at'], unique=False, schema='report')
    op.create_index('idx_pool_summaries_child', 'pool_summaries', ['child_id'], unique=False, schema='report')
    op.create_table_comment(
        'final_reports',
        'Comprehensive AI-generated final reports combining all pool summaries with two-stage review workflow',
        existing_comment=None,
        schema='report'
    )
    op.drop_index(op.f('ix_report_final_reports_created_at'), table_name='final_reports', schema='report')
    op.create_index('idx_final_reports_hod_reviewed', 'final_reports', ['hod_reviewed_at'], unique=False, schema='report')
    op.create_index('idx_final_reports_generated', 'final_reports', ['generated_at'], unique=False, schema='report')
    op.create_index('idx_final_reports_doctor_reviewed', 'final_reports', ['doctor_reviewed_at'], unique=False, schema='report')
    op.create_index('idx_final_reports_child', 'final_reports', ['child_id'], unique=False, schema='report')
    op.alter_column('parents', 'assigned_doctor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Assigned doctor (optional, can be set later)',
               existing_nullable=True,
               schema='clinical')
    op.create_index('idx_sections_pool_id', 'sections', ['pool_id'], unique=False, schema='assessment')
    op.create_index('idx_responses_last_conversation_id', 'responses', ['last_conversation_id'], unique=False, schema='assessment')
    op.alter_column('responses', 'last_conversation_id',
               existing_type=sa.UUID(),
               comment='ID of the most recent conversation log, overwritten on resume',
               existing_comment='ID of the most recent conversation log, overwritten on resume (not a FK to avoid circular dependency)',
               existing_nullable=True,
               schema='assessment')
    op.alter_column('responses', 'assessment_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='assessment')
    op.alter_column('responses', 'unanswered_questions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment='Array of question objects that were not answered in the conversation',
               existing_server_default=sa.text("'[]'::jsonb"),
               schema='assessment')
    op.alter_column('question_answers', 'translated_answer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='English translation of the answer if provided in another language',
               existing_nullable=True,
               schema='assessment')
    op.create_table_comment(
        'pools',
        'Pool containers that group multiple assessment sections',
        existing_comment=None,
        schema='assessment'
    )
    op.drop_index(op.f('ix_assessment_pools_created_at'), table_name='pools', schema='assessment')
    op.create_index('idx_pools_order', 'pools', ['order_number'], unique=False, schema='assessment')
    op.create_index('idx_pools_active', 'pools', ['is_active'], unique=False, schema='assessment')
    op.alter_column('pools', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this pool is active/visible',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='assessment')
    op.alter_column('pools', 'order_number',
               existing_type=sa.INTEGER(),
               comment='Display order of pools',
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='assessment')
    op.alter_column('pools', 'description',
               existing_type=sa.TEXT(),
               comment='Description of what this pool contains',
               existing_nullable=True,
               schema='assessment')
    op.alter_column('pools', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Name/title of the pool',
               existing_nullable=False,
               schema='assessment')
    op.create_index('idx_conversation_logs_response_id', 'conversation_logs', ['response_id'], unique=False, schema='assessment')
    op.alter_column('conversation_logs', 'conversation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Raw conversation data from submission',
               existing_nullable=False,
               schema='assessment')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device'),
    schema='auth'
    )
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('idx_sessions_refresh_token', 'sessions', ['refresh_token_hash'], unique=False, schema='auth')
    op.create_index('idx_sessions_active', 'sessions', ['user_id', 'revoked_at'], unique=False, schema='auth')
    # ### end Alembic commands ###
