"""
InQuantic.ai Application Package
Generated by inquantic-foundry

This package contains the core FastAPI application with:
- Zero-trust security
- Structured app_logging
- OpenTelemetry tracing
- RBAC authorization
"""

__version__ = "1.0.0"