"""
InQuantic.ai FastAPI Application
Zero-Trust  HIPAA  GDPR  SOC2 Compliant

Generated by inquantic-foundry
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.responses import JSONResponse
from asgi_correlation_id import CorrelationIdMiddleware
from opentelemetry import trace
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
from prometheus_client import Counter, Histogram, make_asgi_app
import time

from config.settings import settings
from app_logging.logger import get_logger, log_request
from app.api.v1.router import api_router as router


# Initialize structured logger
logger = get_logger(__name__)

# Initialize OpenTelemetry
trace.set_tracer_provider(TracerProvider())
tracer = trace.get_tracer(__name__)

#comment this out to stop printing to console
trace.get_tracer_provider().add_span_processor(
    BatchSpanProcessor(ConsoleSpanExporter())
)

# Prometheus metrics
REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"]
)

REQUEST_DURATION = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "endpoint"]
)


# ============================================================================
# LIFESPAN EVENTS (Modern FastAPI Pattern)
# ============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for startup and shutdown events.
    Replaces deprecated @app.on_event decorators.
    """
    # Startup
    logger.info(
        "application_startup",
        app_name=settings.APP_NAME,
        environment=settings.ENVIRONMENT,
        version="1.0.0"
    )
    
    # TODO: Initialize database pool
    # TODO: Initialize Redis connection
    # TODO: Warm up ML models (if applicable)
    # TODO: Verify external service connectivity
    
    yield  # Application is running
    
    # Shutdown
    logger.info("application_shutdown", app_name=settings.APP_NAME)
    
    # TODO: Close database connections
    # TODO: Close Redis connections
    # TODO: Flush remaining logs


# Create FastAPI app with lifespan context manager
app = FastAPI(
    title=settings.APP_NAME,
    version="0.0.2",
    description="InQuantic.ai - Nurture Bridge Microservice",
    docs_url="/api/docs" if settings.ENVIRONMENT != "production" else None,
    redoc_url="/api/redoc" if settings.ENVIRONMENT != "production" else None,
    openapi_url="/api/openapi.json" if settings.ENVIRONMENT != "production" else None,
    lifespan=lifespan,  # Use modern lifespan context manager
)

# ============================================================================
# SECURITY MIDDLEWARE
# ============================================================================

# Correlation ID tracking (for distributed tracing)
app.add_middleware(
    CorrelationIdMiddleware,
    header_name="X-Request-ID",
    generator=lambda: format(trace.get_current_span().get_span_context().trace_id, "032x"),
)

# CORS (restrict in production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH"],
    allow_headers=["*"],
)

# Trusted Host protection
if settings.ENVIRONMENT == "production":
    app.add_middleware(
        TrustedHostMiddleware,
        allowed_hosts=settings.ALLOWED_HOSTS
    )

# ============================================================================
# REQUEST/RESPONSE MIDDLEWARE
# ============================================================================

@app.middleware("http")
async def logging_middleware(request: Request, call_next):
    """
    Logs every request/response with correlation IDs and performance metrics.
    HIPAA/SOC2 compliant - no PII in logs.
    """
    start_time = time.time()
    
    # Log incoming request
    log_request(request)
    
    # Process request
    try:
        response = await call_next(request)
        duration = time.time() - start_time
        
        # Record metrics
        REQUEST_COUNT.labels(
            method=request.method,
            endpoint=request.url.path,
            status=response.status_code
        ).inc()
        
        REQUEST_DURATION.labels(
            method=request.method,
            endpoint=request.url.path
        ).observe(duration)
        
        # Log response
        logger.info(
            "request_completed",
            method=request.method,
            path=request.url.path,
            status_code=response.status_code,
            duration_ms=round(duration * 1000, 2)
        )
        
        return response
        
    except Exception as exc:
        duration = time.time() - start_time
        logger.error(
            "request_failed",
            method=request.method,
            path=request.url.path,
            error=str(exc),
            duration_ms=round(duration * 1000, 2)
        )
        raise

# ============================================================================
# EXCEPTION HANDLERS
# ============================================================================

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Global exception handler - logs errors without exposing internal details.
    """
    logger.error(
        "unhandled_exception",
        error_type=type(exc).__name__,
        error_message=str(exc),
        path=request.url.path,
        method=request.method
    )
    
    # Don't expose internal errors in production
    if settings.ENVIRONMENT == "production":
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={
                "error": "Internal server error",
                "request_id": request.headers.get("X-Request-ID")
            }
        )
    else:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={
                "error": str(exc),
                "type": type(exc).__name__,
                "request_id": request.headers.get("X-Request-ID")
            }
        )



# ============================================================================
# ROUTES
# ============================================================================

# Include API routes
app.include_router(router, prefix="/api/v1")

# Prometheus metrics endpoint
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)

# ============================================================================
# ROOT ENDPOINT
# ============================================================================

@app.get("/", tags=["Root"])
async def root():
    """
    Root endpoint - basic service info.
    """
    return {
        "service": settings.APP_NAME,
        "version": "1.0.0",
        "status": "operational",
        "environment": settings.ENVIRONMENT,
        "docs": "/api/docs" if settings.ENVIRONMENT != "production" else "disabled"
    }

# ============================================================================
# INSTRUMENT WITH OPENTELEMETRY
# ============================================================================

FastAPIInstrumentor.instrument_app(app)

# ============================================================================
# READY TO RUN
# ============================================================================

if __name__ == "__main__":
    import uvicorn
    
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=8000,
        reload=settings.ENVIRONMENT == "development",
        log_level="info",
        access_log=True
    )