"""
Application Settings
Zero-Trust Configuration Management

Uses python-decouple for secure environment variable handling.
NEVER commit .env files to version control.

Generated by inquantic-foundry
"""

from decouple import config, Csv
from typing import List


class Settings:
    """
    Application configuration.
    All sensitive values MUST come from environment variables.
    """

    # ========================================================================
    # APPLICATION
    # ========================================================================
    APP_NAME: str = config("APP_NAME", default="InQuantic Microservice")
    ENVIRONMENT: str = config("ENVIRONMENT", default="development")
    DEBUG: bool = config("DEBUG", default=False, cast=bool)
    VERSION: str = "1.0.0"

    # ========================================================================
    # SERVER
    # ========================================================================
    HOST: str = config("HOST", default="0.0.0.0")
    PORT: int = config("PORT", default=8000, cast=int)
    WORKERS: int = config("WORKERS", default=4, cast=int)

    # ========================================================================
    # SECURITY
    # ========================================================================
    SECRET_KEY: str = config("SECRET_KEY", default="CHANGE-ME-IN-PRODUCTION-USE-STRONG-KEY")
    JWT_SECRET_KEY: str = config("JWT_SECRET_KEY", default="CHANGE-ME-IN-PRODUCTION")
    JWT_ALGORITHM: str = config("JWT_ALGORITHM", default="HS256")
    ACCESS_TOKEN_EXPIRE_MINUTES: int = config("ACCESS_TOKEN_EXPIRE_MINUTES", default=30, cast=int)
    REFRESH_TOKEN_EXPIRE_DAYS: int = config("REFRESH_TOKEN_EXPIRE_DAYS", default=7, cast=int)

    # Rate limiting
    RATE_LIMIT_ENABLED: bool = config("RATE_LIMIT_ENABLED", default=True, cast=bool)
    RATE_LIMIT_PER_MINUTE: int = config("RATE_LIMIT_PER_MINUTE", default=60, cast=int)

    # ========================================================================
    # CORS & TRUSTED HOSTS
    # ========================================================================
    CORS_ORIGINS: List[str] = config(
        "CORS_ORIGINS",
        default="http://localhost:3000,http://localhost:8000",
        cast=Csv()
    )
    ALLOWED_HOSTS: List[str] = config(
        "ALLOWED_HOSTS",
        default="localhost,127.0.0.1",
        cast=Csv()
    )

    # ========================================================================
    # DATABASE
    # ========================================================================
    DATABASE_URL: str = config(
        "DEV_DATABASE_URL",
        default=config("DATABASE_URL", default="postgresql+asyncpg://neondb_owner:npg_lahjNUDXQb45@ep-summer-voice-a10p3gpv-pooler.ap-southeast-1.aws.neon.tech/neondb?ssl=require")
    )
    DB_POOL_SIZE: int = config("DB_POOL_SIZE", default=20, cast=int)
    DB_MAX_OVERFLOW: int = config("DB_MAX_OVERFLOW", default=10, cast=int)
    DB_ECHO: bool = config("DB_ECHO", default=False, cast=bool)

    # ========================================================================
    # REDIS (for Celery, caching, rate limiting)
    # ========================================================================
    REDIS_URL: str = config("REDIS_URL", default="redis://localhost:6379/0")
    REDIS_TLS_ENABLED: bool = config("REDIS_TLS_ENABLED", default=False, cast=bool)
    CACHE_TTL: int = config("CACHE_TTL", default=300, cast=int)  # seconds

    # ========================================================================
    # CELERY (Background Tasks)
    # ========================================================================
    CELERY_BROKER_URL: str = config("CELERY_BROKER_URL", default="redis://localhost:6379/1")
    CELERY_RESULT_BACKEND: str = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/2")

    # ========================================================================
    # LOGGING
    # ========================================================================
    LOG_LEVEL: str = config("LOG_LEVEL", default="INFO")
    LOG_FORMAT: str = config("LOG_FORMAT", default="json")  # json or console

    # Audit app_logging
    AUDIT_LOG_ENABLED: bool = config("AUDIT_LOG_ENABLED", default=True, cast=bool)
    AUDIT_LOG_FILE: str = config("AUDIT_LOG_FILE", default="logs/audit.log")

    # ========================================================================
    # OBSERVABILITY
    # ========================================================================
    # OpenTelemetry
    OTEL_ENABLED: bool = config("OTEL_ENABLED", default=True, cast=bool)
    OTEL_EXPORTER_OTLP_ENDPOINT: str = config(
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        default="http://localhost:4317"
    )
    OTEL_SERVICE_NAME: str = config("OTEL_SERVICE_NAME", default=APP_NAME)

    # Sentry (Error Tracking)
    SENTRY_DSN: str = config("SENTRY_DSN", default="")
    SENTRY_ENVIRONMENT: str = config("SENTRY_ENVIRONMENT", default=ENVIRONMENT)
    SENTRY_TRACES_SAMPLE_RATE: float = config("SENTRY_TRACES_SAMPLE_RATE", default=0.1, cast=float)

    # ========================================================================
    # PII/PHI PROTECTION
    # ========================================================================
    PII_DETECTION_ENABLED: bool = config("PII_DETECTION_ENABLED", default=True, cast=bool)
    PII_MASK_LOGS: bool = config("PII_MASK_LOGS", default=True, cast=bool)
    PHI_ENCRYPTION_ENABLED: bool = config("PHI_ENCRYPTION_ENABLED", default=True, cast=bool)

    # ========================================================================
    # SMTP EMAIL
    # ========================================================================
    SMTP_HOST: str = config("SMTP_HOST", default="smtp.gmail.com")
    SMTP_PORT: int = config("SMTP_PORT", default=587, cast=int)
    SMTP_USERNAME: str = config("SMTP_USERNAME", default="")
    SMTP_PASSWORD: str = config("SMTP_PASSWORD", default="")
    SMTP_USE_TLS: bool = config("SMTP_USE_TLS", default=True, cast=bool)
    SMTP_USE_SSL: bool = config("SMTP_USE_SSL", default=False, cast=bool)
    SMTP_FROM_EMAIL: str = config("SMTP_FROM_EMAIL", default="noreply@example.com")
    SMTP_FROM_NAME: str = config("SMTP_FROM_NAME", default=APP_NAME)
    SMTP_TIMEOUT: int = config("SMTP_TIMEOUT", default=30, cast=int)

    # ========================================================================
    # EXTERNAL SERVICES
    # ========================================================================
    # Add your external service configurations here
    # Example:
    # EXTERNAL_API_URL: str = config("EXTERNAL_API_URL", default="https://api.example.com")
    # EXTERNAL_API_KEY: str = config("EXTERNAL_API_KEY", default="")

    # ========================================================================
    # FEATURE FLAGS
    # ========================================================================
    FEATURE_NEW_UI: bool = config("FEATURE_NEW_UI", default=False, cast=bool)
    FEATURE_BETA_API: bool = config("FEATURE_BETA_API", default=False, cast=bool)

    # ========================================================================
    # COMPLIANCE & SECURITY HEADERS
    # ========================================================================
    HSTS_ENABLED: bool = config("HSTS_ENABLED", default=True, cast=bool)
    HSTS_MAX_AGE: int = config("HSTS_MAX_AGE", default=31536000, cast=int)  # 1 year
    CSP_ENABLED: bool = config("CSP_ENABLED", default=True, cast=bool)

    # ========================================================================
    # VALIDATION
    # ========================================================================
    def validate(self):
        """
        Validate critical configuration at startup.
        Fails fast if production settings are insecure.
        """
        if self.ENVIRONMENT == "production":
            # Check for default/weak secrets
            if self.SECRET_KEY == "CHANGE-ME-IN-PRODUCTION-USE-STRONG-KEY":
                raise ValueError("SECRET_KEY must be changed in production!")

            if self.JWT_SECRET_KEY == "CHANGE-ME-IN-PRODUCTION":
                raise ValueError("JWT_SECRET_KEY must be changed in production!")

            if len(self.SECRET_KEY) < 32:
                raise ValueError("SECRET_KEY must be at least 32 characters in production!")

            # Ensure HTTPS-only CORS origins
            for origin in self.CORS_ORIGINS:
                if not origin.startswith("https://") and origin != "localhost":
                    raise ValueError(f"Production CORS origin must use HTTPS: {origin}")

            # Ensure database uses TLS
            if not self.DATABASE_URL.startswith("postgresql+asyncpg://") or "sslmode" not in self.DATABASE_URL:
                print("⚠️  WARNING: Database connection should use SSL in production!")

            # Ensure Redis uses TLS
            if not self.REDIS_TLS_ENABLED and not self.REDIS_URL.startswith("rediss://"):
                print("⚠️  WARNING: Redis should use TLS in production!")

        return True


# ============================================================================
# SINGLETON INSTANCE
# ============================================================================

settings = Settings()

# Validate on import
settings.validate()