"""
Database Base Configuration
SQLAlchemy 2.0 Async Setup

Features:
- Async engine with connection pooling
- Async session factory
- FastAPI dependency for sessions
- Proper transaction management

Generated by inquantic-foundry
"""

from typing import AsyncGenerator
from sqlalchemy.ext.asyncio import (
    create_async_engine,
    async_sessionmaker,
    AsyncSession,
    AsyncEngine
)

import os
from dotenv import load_dotenv

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.pool import NullPool, QueuePool

from config.settings import settings
from app_logging.logger import get_logger

load_dotenv()
logger = get_logger(__name__)


# ============================================================================
# BASE MODEL
# ============================================================================

class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy models.
    All models should inherit from this class.
    """
    pass


# ============================================================================
# ENGINE CONFIGURATION
# ============================================================================

# Configure connection pool based on environment
# Async engine uses QueuePool by default
if settings.ENVIRONMENT == "test":
    # Use NullPool for tests (no connection reuse)
    pool_args = {"poolclass": NullPool}
    logger.info("database_pool_disabled", reason="test_environment")
else:
    # Use default QueuePool
    pool_args = {
        "pool_size": settings.DB_POOL_SIZE,
        "max_overflow": settings.DB_MAX_OVERFLOW,
        "pool_recycle": 3600,
        "pool_pre_ping": True,
    }
    logger.info(
        "database_pool_configured",
        pool_size=settings.DB_POOL_SIZE,
        max_overflow=settings.DB_MAX_OVERFLOW
    )

# Create async engine
# Create async engine
# Ensure we use the asyncpg driver even if the env var specifies postgresql://
database_url = settings.DATABASE_URL
if database_url and database_url.startswith("postgresql://"):
    database_url = database_url.replace("postgresql://", "postgresql+asyncpg://")

engine: AsyncEngine = create_async_engine(
    database_url,
    echo=settings.DB_ECHO,
    **pool_args
)

# ============================================================================
# SESSION FACTORY
# ============================================================================

# Create async session factory
async_session = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False,
)


# ============================================================================
# FASTAPI DEPENDENCY
# ============================================================================

async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency for database sessions.

    Usage:
        @router.get("/users")
        async def get_users(db: AsyncSession = Depends(get_db)):
            result = await db.execute(select(User))
            return result.scalars().all()

    Yields:
        AsyncSession: Database session
    """
    async with async_session() as session:
        try:
            logger.debug("database_session_created")
            yield session
            await session.commit()
            logger.debug("database_session_committed")
        except Exception as e:
            await session.rollback()
            logger.error("database_session_rollback", error=str(e))
            raise
        finally:
            await session.close()
            logger.debug("database_session_closed")


# ============================================================================
# DATABASE UTILITIES
# ============================================================================

async def init_db() -> None:
    """
    Initialize database - create all tables.
    Should be called on application startup.
    """
    async with engine.begin() as conn:
        # Import all models here to ensure they're registered
        # from db.models import User, etc.

        await conn.run_sync(Base.metadata.create_all)
        logger.info("database_tables_created")


async def drop_db() -> None:
    """
    Drop all database tables.
    WARNING: This will delete all data!
    Should only be used in development/testing.
    """
    if settings.ENVIRONMENT == "production":
        raise RuntimeError("Cannot drop database in production!")

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        logger.warning("database_tables_dropped")


async def close_db() -> None:
    """
    Close database connections.
    Should be called on application shutdown.
    """
    await engine.dispose()
    logger.info("database_connections_closed")


# ============================================================================
# TRANSACTION CONTEXT MANAGER
# ============================================================================

class transaction:
    """
    Context manager for explicit transactions.

    Usage:
        async with transaction() as session:
            user = User(name="John")
            session.add(user)
            # Automatically commits on success, rolls back on error
    """

    def __init__(self):
        self.session: AsyncSession | None = None

    async def __aenter__(self) -> AsyncSession:
        self.session = async_session()
        logger.debug("transaction_started")
        return self.session

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if exc_type is not None:
            await self.session.rollback()
            logger.error("transaction_rollback", error=str(exc_val))
        else:
            await self.session.commit()
            logger.debug("transaction_committed")

        await self.session.close()
        logger.debug("transaction_closed")


# ============================================================================
# EXAMPLE USAGE
# ============================================================================

"""
# In your router:

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from db.base import get_db
from db.models import User

router = APIRouter()

@router.get("/users")
async def get_users(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(User))
    users = result.scalars().all()
    return users

@router.post("/users")
async def create_user(user_data: dict, db: AsyncSession = Depends(get_db)):
    user = User(**user_data)
    db.add(user)
    await db.commit()
    await db.refresh(user)
    return user

# In app startup (main.py lifespan):

from db.base import init_db, close_db

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    await init_db()  # Create tables

    yield

    # Shutdown
    await close_db()  # Close connections
"""