"""
Database Models
SQLAlchemy 2.0 ORM models

Example models with common patterns:
- Timestamps (created_at, updated_at)
- Soft deletes
- UUID primary keys
- Indexes
- Relationships

Generated by inquantic-foundry
"""

from datetime import datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import String, Text, Boolean, DateTime, Integer, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from db.base import Base


# ============================================================================
# MIXINS (Reusable model components)
# ============================================================================

class TimestampMixin:
    """Add created_at and updated_at timestamps to models"""

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False
    )


class SoftDeleteMixin:
    """Add soft delete capability to models"""

    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        default=None,
        index=True
    )

    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True
    )

    def soft_delete(self):
        """Mark record as deleted"""
        self.is_deleted = True
        self.deleted_at = datetime.utcnow()

    def restore(self):
        """Restore soft-deleted record"""
        self.is_deleted = False
        self.deleted_at = None


# ============================================================================
# EXAMPLE MODELS
# ============================================================================

class User(Base, TimestampMixin, SoftDeleteMixin):
    """
    Example User model.
    Replace/extend this based on your application needs.
    """

    __tablename__ = "users"

    # Primary key (UUID)
    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=lambda: str(uuid4()),
        nullable=False
    )

    # User fields
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True
    )

    username: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True
    )

    full_name: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True
    )

    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False,
        index=True
    )

    is_superuser: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    # Relationships
    # posts: Mapped[list["Post"]] = relationship(back_populates="author")

    # Indexes
    __table_args__ = (
        Index('ix_users_email_active', 'email', 'is_active'),
        Index('ix_users_deleted', 'is_deleted', 'deleted_at'),
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, email={self.email}, username={self.username})>"


class Post(Base, TimestampMixin, SoftDeleteMixin):
    """
    Example Post model demonstrating relationships.
    """

    __tablename__ = "posts"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=lambda: str(uuid4()),
        nullable=False
    )

    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True
    )

    content: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )

    author_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        # ForeignKey("users.id"),  # Uncomment to enable relationship
        nullable=False,
        index=True
    )

    is_published: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True
    )

    published_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True
    )

    view_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False
    )

    # Relationship
    # author: Mapped["User"] = relationship(back_populates="posts")

    __table_args__ = (
        Index('ix_posts_author_published', 'author_id', 'is_published'),
        Index('ix_posts_published_date', 'is_published', 'published_at'),
    )

    def __repr__(self) -> str:
        return f"<Post(id={self.id}, title={self.title})>"


# ============================================================================
# HEALTHCARE EXAMPLE MODELS (HIPAA Compliant)
# ============================================================================

class Patient(Base, TimestampMixin, SoftDeleteMixin):
    """
    Example Patient model for healthcare applications.
    PHI fields should be encrypted at rest.
    """

    __tablename__ = "patients"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=lambda: str(uuid4()),
        nullable=False
    )

    # Medical Record Number
    mrn: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True
    )

    # PHI - Should be encrypted
    first_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    last_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    date_of_birth: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False
    )

    # Non-PHI
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False
    )

    __table_args__ = (
        Index('ix_patients_mrn_active', 'mrn', 'is_active'),
        Index('ix_patients_name', 'last_name', 'first_name'),
    )

    def __repr__(self) -> str:
        return f"<Patient(id={self.id}, mrn={self.mrn})>"


# ============================================================================
# AUDIT LOG MODEL (Immutable)
# ============================================================================

class AuditLog(Base, TimestampMixin):
    """
    Audit log model for tracking all system events.
    This table should be append-only (no updates/deletes).
    """

    __tablename__ = "audit_logs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        default=lambda: str(uuid4()),
        nullable=False
    )

    event_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    actor_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True
    )

    resource_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    resource_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True
    )

    action: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True
    )

    result: Mapped[str] = mapped_column(
        String(50),
        nullable=False
    )

    details: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )

    ip_address: Mapped[Optional[str]] = mapped_column(
        String(45),  # IPv6 length
        nullable=True
    )

    __table_args__ = (
        Index('ix_audit_logs_actor_event', 'actor_id', 'event_type'),
        Index('ix_audit_logs_resource', 'resource_type', 'resource_id'),
        Index('ix_audit_logs_created', 'created_at'),
    )

    def __repr__(self) -> str:
        return f"<AuditLog(id={self.id}, event_type={self.event_type}, actor={self.actor_id})>"


# ============================================================================
# QUERY HELPERS
# ============================================================================

"""
# Example queries using SQLAlchemy 2.0 syntax:

from sqlalchemy import select, update, delete
from sqlalchemy.ext.asyncio import AsyncSession

# Select
async def get_active_users(db: AsyncSession):
    result = await db.execute(
        select(User).where(User.is_active == True, User.is_deleted == False)
    )
    return result.scalars().all()

# Insert
async def create_user(db: AsyncSession, email: str, username: str):
    user = User(email=email, username=username)
    db.add(user)
    await db.commit()
    await db.refresh(user)
    return user

# Update
async def update_user(db: AsyncSession, user_id: str, full_name: str):
    await db.execute(
        update(User)
        .where(User.id == user_id)
        .values(full_name=full_name, updated_at=datetime.utcnow())
    )
    await db.commit()

# Soft delete
async def soft_delete_user(db: AsyncSession, user_id: str):
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if user:
        user.soft_delete()
        await db.commit()

# Join query
async def get_user_posts(db: AsyncSession, user_id: str):
    result = await db.execute(
        select(Post)
        .where(Post.author_id == user_id, Post.is_deleted == False)
        .order_by(Post.created_at.desc())
    )
    return result.scalars().all()
"""