"""
PII/PHI Protection Package
Automated detection and anonymization of sensitive data

- Presidio Analyzer (detection)
- Presidio Anonymizer (masking/encryption)
- HIPAA/GDPR compliant

Generated by inquantic-foundry
"""