"""
Email Module
Production-ready SMTP email service

Generated by inquantic-foundry
"""

from email_service.service import send_email
from email_service.templates import render_template, list_templates

__all__ = [
    "send_email",
    "render_template",
    "list_templates",
]
