"""
Email Module
Production-ready SMTP email service

Generated by inquantic-foundry
"""

from email.service import (
    EmailService,
    email_service,
    send_email,
    send_email_async,
    send_template_email,
    send_template_email_async,
)
from email.templates import render_template, list_templates

__all__ = [
    "EmailService",
    "email_service",
    "send_email",
    "send_email_async",
    "send_template_email",
    "send_template_email_async",
    "render_template",
    "list_templates",
]
