"""
Email Template System
Jinja2-based template rendering for emails

Generated by inquantic-foundry
"""

from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape
from structlog import get_logger

logger = get_logger(__name__)

# Template directory path
TEMPLATE_DIR = Path(__file__).parent / "templates"

# Initialize Jinja2 environment
env = Environment(
    loader=FileSystemLoader(str(TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "xml"]),
)


def render_template(template_name: str, context: dict) -> str:
    """
    Render an email template with the given context.

    Args:
        template_name: Name of template file (e.g., 'welcome.html')
        context: Dictionary of variables to pass to template

    Returns:
        Rendered HTML string

    Raises:
        TemplateNotFound: If template doesn't exist
        TemplateSyntaxError: If template has syntax errors
    """
    try:
        template = env.get_template(template_name)
        rendered = template.render(**context)
        logger.debug("template_rendered", template=template_name)
        return rendered
    except Exception as e:
        logger.error(
            "template_render_failed",
            template=template_name,
            error=str(e),
        )
        raise


def list_templates() -> list:
    """List all available email templates."""
    return [t for t in TEMPLATE_DIR.glob("*.html") if t.name != "base.html"]
