"""
Logging Package
Enterprise-Grade Structured Logging

- Structured JSON logs (structlog)
- Correlation ID tracking
- Audit app_logging (HIPAA/SOC2 compliant)
- PII/PHI masking
- OpenTelemetry integration

Generated by inquantic-foundry
"""